config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :registrations, only: [:new,:create]
  resources :sessions, only: [:new, :create, :destroy]

  get "welcome", to: "sessions#welcome"
  # get "authorized", to: "sessions#page_requires_login"
  
  resources :books
  resources :users
  
  get '/profile', to: 'profile#show', as: :user_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord

  # belongs_to :user

  def formatted_started_date
    started_date.strftime("%m/%d/%Y") if started_date
  end

  def formatted_finished_date
    finished_date.strftime("%m/%d/%Y") if finished_date
  end

  def calculate_duration
    duration = finished_date - started_date
    duration.to_i
  end

end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  # Validates Email exists, is unique and follows the appropriate pattern
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }

  has_many :books
  has_one :profile, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized, except: :index
  before_action :authenticate_user

  helper_method :current_user
  helper_method :user_logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to root_path unless user_logged_in?
  end

  private

  def authenticate_user
    unless user_logged_in? || sessions_controller_actions.include?(params[:action]) || request.path == root_path
      redirect_to root_path, alert: "Please log in to access this page."
    end
  end

  def sessions_controller_actions
    ['new', 'create']
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @years_collection = current_user.books.pluck(:finished_date).map { |date| date&.year }.compact.uniq.sort.reverse
    @selected_year = params[:year].to_i if params[:year].present?
    
    @books = current_user.books.order("created_at ASC")
    
    if @selected_year.present?
      @books = @books.where("strftime('%Y', finished_date) = ?", @selected_year.to_s)
    end
    
    @books = @books.page(params[:page]).per(10)
    
    calculate_totals
  end

  def show
    @book = find_book
  end

  def new
    @book = Book.new
  end

  def edit
    @book = find_book
  end

  def create
    @book = current_user.books.build(book_params)

    if @book.save
      redirect_to books_path
      flash[:success] = "Book was successfully created."
    else
      flash[:error] = @book.errors.full_messages
      render :new
    end
  end

  def update
    @book = find_book

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = current_user.books.find_by(id: params[:id])

    if @book
      @book.destroy
      redirect_to books_path, notice: 'Book was successfully deleted.'
    else
      redirect_to books_path, alert: 'Book not found.'
    end
  end

  private
  def book_params
    params.require(:book).permit(
      :title,
      :author,
      :description,
      :number_of_pages,
      :started_date,
      :finished_date
    ).merge(user_id: current_user.id)
  end

  def find_book
    Book.find(params[:id])
  end

  def total_books_read
    @total_books_read = Book.count if @books.present?
  end

  def number_of_pages_read
    @number_of_pages_read = Book.sum(:number_of_pages) if @books.present?
  end

  def calculate_totals
    if @books.present?
      @total_books_read = @books.total_count
      @number_of_pages_read = current_user.books.where("strftime('%Y', finished_date) = ?", @selected_year.to_s).sum(:number_of_pages)
    else
      @total_books_read = 0
      @number_of_pages_read = 0
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfileController < ApplicationController
  # before_action :authorized

  def show
    @user = current_user
    @profile = @user.profile
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:email, :password))
    session[:user_id] = @user.id
    redirect_to books_path
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to books_path
    else
      redirect_to root_path
    end
  end

  def page_requires_login
  end

  def welcome
  end

  # def destroy
  #   session.delete :user_id
  #   redirect_to root_path, flash: { success: "Logged Out" }
  # end

  def destroy
    session.delete :user_id
    flash[:success] = "Logged Out"
    render 'sessions/new'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.create_profile
      session[:user_id] = @user.id
      redirect_to books_path
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
</div>

app/views/books/_form.html.erb
<%= form_with model: book do |form| %>
  <div>
    <%= form.label :title %>
    <br/>
    <%= form.text_field :title %>
    <% book.errors.full_messages_for(:title).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :author %>
    <br/>
    <%= form.text_field :author %>
    <% book.errors.full_messages_for(:author).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :description %>
    <br/>
    <%= form.text_field :description %>
    <% book.errors.full_messages_for(:description).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :number_of_pages %>
    <br/>
    <%= form.number_field :number_of_pages %>
    <% book.errors.full_messages_for(:number_of_pages).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.submit "Create Book", class: "btn btn-dark btn-sm" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render "form", book: @book %>
<%= link_to 'Show', @book, class: 'btn btn-info btn-sm' %>
<%= link_to 'Back', books_path, class: 'btn btn-warning btn-sm' %>

app/views/books/index.html.erb
<h1>
  Welcome <%= current_user.username %>!
</h1>
<h1 class="text-decoration-underline" id="year-heading">
  Books Read in <%= @selected_year || Time.now.year %>
</h1>
<div class="d-grid gap-2 col-3">
  <%= link_to new_book_path, class: "btn btn-warning btn-block fw-bold", style: "width: 137%;" do %>
    <i class="bi bi-plus-circle-fill me-2"></i>
    New Book
  <% end %>
</div>
<br/>
<h5>
  Number of Books Read: <%= @total_books_read %>
</h5>
<h5 class="mb-3">
  Number of Pages Read: <%= @number_of_pages_read %>
</h5>
<%# YEAR DROPDOWN %>
<div class="form-group row" style="margin-bottom: 20px;">
  <%= form_tag(books_path, method: "get", class: "form-inline") do %>
    <div class="col-6">
      <%= select_tag :year, options_for_select(@years_collection.map(&:to_s), @selected_year.to_s), class: "form-control", style: "max-width: 22%;", id: "year-dropdown" %>
    </div>
    <div class="col-6">
      <%= submit_tag "Select Year", class: "btn btn-dark btn-block" %>
    </div>
  <% end %>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr class="table-info">
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each_with_index do |book, index| %>
      <tr>
        <th scope="row">
          <%= ((@books.current_page - 1) * @books.limit_value) + index + 1 %>
        </th>
        <td>
          <%= book.title %>
        </td>
        <td>
          <%= book.author %>
        </td>
        <td>
          <%= truncate(book.description, length: 100) %>
        </td>
      </tr>
      <tr>
        <th scope="col"></th>
        <!-- SHOW BOOK -->
        <td class="text-center">
          <%= link_to book_path(book), class: "btn btn-info btn-sm text-nowrap" do %>
            <i class="bi bi-info-circle-fill"></i>
          <% end %>
        </td>
        <!-- EDIT BOOK -->
        <td class="text-center">
          <%= link_to edit_book_path(book), class: "btn btn-secondary btn-sm text-nowrap" do %>
            <i class="bi bi-pencil-fill"></i>
          <% end %>
        </td>
        <!-- DELETE BOOK -->
        <td style="text-align: right;">
          <%= link_to book_path(book), method: :delete, class: "btn btn-danger btn-sm text-nowrap", data: { confirm: 'Are you sure?' } do %>
            <i class="bi bi-trash-fill"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination">
  <%= paginate @books %>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const yearDropdown = document.getElementById("year");
    const yearHeading = document.getElementById("year-heading");

    yearDropdown.addEventListener("change", function() {
      const selectedYear = yearDropdown.value;
      yearHeading.innerHTML = `Books Read in ${selectedYear}`;
    });
  });
</script>

q

app/views/books/new.html.erb
<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-8 col-lg-6 col-xl-4">
        <div class="container my-form-container">
          <%= form_with(model: @book, url: books_path, local: true, html: { class: "form-border border p-3 border-dark" }) do |form| %>
            <%= form.hidden_field :authenticity_token, value: form_authenticity_token %>
            <div class="form-outline mb-4">
              <label class="form-label fw-bold" for="book_title">Title</label>
              <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "Title..." %>
            </div>
            <div class="form-outline mb-4">
              <label class="form-label fw-bold" for="book_author">Author</label>
              <%= form.text_field :author, class: "form-control form-control-lg", placeholder: "Author..." %>
            </div>
            <div class="form-outline mb-4">
              <label class="form-label fw-bold" for="book_description">Description</label>
              <%= form.text_area :description, class: "form-control form-control-lg", placeholder: "Description..." %>
            </div>
            <div class="form-outline mb-4">
              <label class="form-label fw-bold" for="book_number_of_pages">Number of Pages</label>
              <%= form.number_field :number_of_pages, class: "form-control form-control-lg", placeholder: "Number of pages..." %>
            </div>
            <div class="form-outline mb-4">
              <label class="form-label fw-bold" for="book_started_date">Started Date</label>
              <%= form.date_field :started_date, class: "form-control form-control-lg", value: @book.started_date&.strftime("%Y-%m-%d") %>
            </div>
            <div class="form-outline mb-4">
              <label class="form-label fw-bold" for="book_finished_date">Finished Date</label>
              <%= form.date_field :finished_date, class: "form-control form-control-lg", value: @book.finished_date&.strftime("%Y-%m-%d") %>
            </div>
            <div class="text-center text-lg-start mt-4 pt-2">
              <button class="btn btn-warning btn-lg" style="padding-left: 2.5rem; padding-right: 2.5rem; display: block; margin: 0 auto;" type="submit">
                Create Book
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/books/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<h4>
  <%= "Book ##{@book.id}" %>
</h4>
<h5 class="pt-3">
  <div class="pt-3 fw-bold">Title:</div>
  <%= @book.title %>
</h5>
<h5 class="pt-3">
  <h5 class="fw-bold">Author:</h5>
  <%= @book.author %>
</h5>
<h5 class="pt-3">
  <h5 class="fw-bold">Description:</h5>
  <%= @book.description %>
</h5>
<h5 class="pt-3">
  <h5 class="fw-bold">Number of Pages:</h5>
  <%= @book.number_of_pages %>
</h5>
<h5 class="pt-3">
  <h5 class="fw-bold">Started Reading:</h5>
  <%= @book.formatted_started_date %>
</h5>
<h5 class="pt-3">
  <h5 class="fw-bold">Finished Reading:</h5>
  <%= @book.formatted_finished_date %>
</h5>
<h5 class="py-3">
  It took you #{@book.calculate_duration} days to read this book
</h5>
<div class="d-flex">
  <%= link_to edit_book_path(@book), class: "btn btn-secondary me-2" do %>
    <i class="bi bi-pencil-fill"></i>
  <% end %>
  <%= link_to books_path, class: 'btn btn-warning' do %>
    <i class="bi bi-book-half"></i>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="container align-items-center d-flex pt-5" style="height: 100vh; flex-direction: column;">
  <h1 class="mt-5">Welcome to Your <%=Time.now.year%> Bookshelf!</h1>
  <div class="d-flex">
    <%= link_to "Log in", new_session_path, class: "btn btn-dark btn-lg custom-margin" %>
    <%= link_to "Sign Up", new_registration_path, class: "btn btn-warning btn-lg custom-margin" %>
    <% # = link_to "Back to Your Books", books_path, class: "btn btn-info btn-lg" %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>

<script>
  $(document).ready(function() {
    // Select the flash message with the "alert" class
    var flashMessage = $('.alert');

    // Set a timeout to fade out the flash message after 5 seconds
    setTimeout(function() {
      flashMessage.fadeOut('slow', function() {
        // After fading out, remove the flash message from the DOM
        flashMessage.remove();
      });
    }, 5000); // 5000 milliseconds (5 seconds)
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <title><%= content_for?(:title) ? yield(:title) : "Your Bookshelf" %></title>
  <meta content="<%= content_for?(:description) ? yield(:description) : "Your Bookshelf" %>" name="description">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Share+Tech+Mono&display=swap" rel="stylesheet">
  <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" rel="stylesheet">
  <script crossorigin="anonymous" defer="defer" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <%= render 'layouts/flash' %>
  <% if user_logged_in? %>
    <%= render(NavbarComponent.new(logged_in: true, current_user: current_user)) %>
  <% end %>

  <div class="px-5">
    <%= yield %>
  </div>
</body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
</div>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Show this profile", @profile %> |
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Profiles</h1>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <%= render profile %>
    <p>
      <%= link_to "Show this profile", profile %>
    </p>
  <% end %>
</div>

<%= link_to "New profile", new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @profile %>

<div>
  <%= link_to "Edit this profile", edit_profile_path(@profile) %> |
  <%= link_to "Back to profiles", profiles_path %>

  <%= button_to "Destroy this profile", @profile, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2>
        <%= pluralize(user.errors.count, "error") %>
        prohibited this user from being saved:
      </h2>
      <ul>
        <% user.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>